name: frontend_flutter
description: AniStream Demo - Full-stack portfolio project with Flutter, FastAPI and Redis.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  drift: ^2.18.0
  drift_flutter: ^0.2.3
  flutter_riverpod: ^2.6.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  wakelock_plus: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
